### PR TITLE
Convert to TypeScript

### LINKED ISSUE #16: Write TypeScript definitions
I don't have experience with TypeScript, but happy to accept a contribution.

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

### PR DESCRIPTION
**Pull request by danoc**
Fixes #16.

***
⚠️  Never written Typescript before so this may be horribly wrong.

### CODE REVIEW

**Comment by thisis-Shitanshu** [comment]
Hey @danoc . If convenient to you, can I join in?
It's an cool project and I am looking for an opportunity to contribute. Also, I have worked on TypeScript.

**Comment by danoc** [comment]
Hey, @thisis-Shitanshu! Thanks for reaching out. Are you able to review this PR? Not sure what kind of permissions GitHub provides.

**Comment by thisis-Shitanshu** [comment]
np version 5.0.3 was not incompatible with "yarn" you need to use npm or an alternative to np.
PR #28 
Solves the issue, you can use that. I have made a migration from yarn to npm.

**Comment by danoc** [comment]
Closing this in favor of #28.

**Pull request closed without merging**
